### ISSUE TITLE
Umbrella ticket for mapping

### ISSUE THREAD

**Issue by dosumis** [causal-reasoning-mapping/causal-workshop-ebi#5]
- [ ] @vtoure - convert google doc to GHMD via pandoc
 - [ ] @sjupe - Add documentation of reactome causal 'relations' - entity-entity & entity to event (process) 
 - [ ] @sandraorchard - Update Signor on progress
 
Mapping strategy: for each RO process:process relation, document (where possible) which relations map to these and how.  Separate ticket for each relation (?)
